ALTER TABLE pocos DROP COLUMN IF EXISTS identificacao;
ALTER TABLE pocos DROP COLUMN IF EXISTS localizacao;
ALTER TABLE pocos DROP COLUMN IF EXISTS status;
ALTER TABLE pocos DROP COLUMN IF EXISTS tipo_ligacao;
ALTER TABLE pocos DROP COLUMN IF EXISTS acessorios;
ALTER TABLE pocos DROP COLUMN IF EXISTS informacao;
ALTER TABLE pocos DROP COLUMN IF EXISTS altura;

ALTER TABLE pocos ADD COLUMN nome               VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE pocos ADD COLUMN logradouro         VARCHAR(200);
ALTER TABLE pocos ADD COLUMN ativo              BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE pocos ADD COLUMN ligacao            VARCHAR(100);
ALTER TABLE pocos ADD COLUMN profundidade_bomba DECIMAL(10,2);

DROP TYPE IF EXISTS status_poco;
DROP TYPE IF EXISTS tipo_ligacao;