ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_perfil;
ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_users_email;
ALTER TABLE users DROP COLUMN IF EXISTS last_access;
ALTER TABLE users DROP COLUMN IF EXISTS perfil;
ALTER TABLE users DROP COLUMN IF EXISTS cargo;
ALTER TABLE users DROP COLUMN IF EXISTS email;
