ALTER TABLE users ADD COLUMN email       VARCHAR(150);
ALTER TABLE users ADD COLUMN cargo       VARCHAR(100);
ALTER TABLE users ADD COLUMN perfil      VARCHAR(20);
ALTER TABLE users ADD COLUMN last_access TIMESTAMP;

UPDATE users SET email = username WHERE email IS NULL;
UPDATE users SET perfil = CASE WHEN role = 'ADMIN' THEN 'ADMINISTRADOR' ELSE 'OPERADOR' END
  WHERE perfil IS NULL;

ALTER TABLE users ALTER COLUMN email  SET NOT NULL;
ALTER TABLE users ALTER COLUMN perfil SET NOT NULL;
ALTER TABLE users ADD CONSTRAINT uq_users_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT chk_users_perfil
    CHECK (perfil IN ('OPERADOR', 'ADMINISTRADOR', 'VISUALIZADOR'));
